server:
  port: 8888

spring:
  application:
    name: market

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/market?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml